name = "ctohm-edge-resizer"
type = "javascript"
workers_dev = true
compatibility_date = "2021-10-05"
route = ""
account_id = ""
api_token = ""
zone_id = ""

[vars]
  WORKER_ENV = "production"
  DEBUG = true
  ROUTE_PREFIX='/' # e.g. /thumbnails
  RELEASE = ""
  TIMESTAMP = ""
  MAX_AGE = "1y"

[build]
  command = "export RELEASE=`git rev-parse --short HEAD`;export TIMESTAMP=`date +%s`; npx esbuild src/index.ts --bundle --format=cjs --outfile=dist/worker.js  --define:ROUTE_PREFIX='\"'$ROUTE_PREFIX'\"'  --define:TIMESTAMP='\"'$TIMESTAMP'\"' --define:RELEASE='\"'$RELEASE'\"'"

  [build.upload]
    format = "service-worker"


