name = "ctohm-edge-resizer"
type = "javascript"
workers_dev = true
compatibility_date = "2021-10-05"
route = ""
account_id = ""
api_token = ""
zone_id = ""

[vars]
  WORKER_ENV = "production"
  DEBUG = true
  ROUTE_PREFIX='/' # e.g. /thumbnails
  RELEASE = ""
  TIMESTAMP = ""
  MAX_AGE = "1y"



[build]
  command = "node esbuild.mjs"
  watch_dir = "functions"

  [build.upload]
    format = "modules"
    dir = ".vitepress/dist"
    main = "./_worker.js"
