name: Deploy

on:
  pull_request:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
    deploy:
      runs-on: ubuntu-latest
      timeout-minutes: 60
      steps:
        - uses: actions/checkout@v2
        # Update "Publish" step from last code snippet
        - name: Publish
          uses: cloudflare/wrangler-action@1.3.0
          with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
          env:
            CF_ZONE_ID: ${{secrets.CF_ZONE_ID}}
            CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}


